// STARTUP
export const LOAD_STARTUPS_SUCCESS = 'LOAD_STARTUPS_SUCCESS';
export const CREATE_STARTUP_SUCCESS = 'CREATED_STARTUP_SUCCESS';
export const UPDATE_STARTUP_SUCCESS = 'UPDATED_STARTUP_SUCCESS';
export const DELETE_STARTUP_SUCCESS = 'DELETE_STARTUP_SUCCESS';

// FOUNDER
export const CREATE_FOUNDER_SUCCESS = 'CREATE_FOUNDER_SUCCESS';

// ERRORS
export const TOGGLE_ERROR_MESSAGE = 'TOGGLE_ERROR_MESSAGE';
